version: "3.4"

services:
  db-kintsugi:
    image: postgres:12
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  db-interlay:
    image: postgres:12
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - /var/lib/postgresql/data2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

  db:
    image: postgres:12
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data3
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
