name: 'coverage'

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  coverage:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Run code coverage
        run: |
            yarn
            yarn test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

